# Lecture 3
##### -配列の定義
##### -配列の演算
##### -関数

## 配列の定義

### 一次元配列

In [2]:
[1]

1-element Array{Int64,1}:
 1

#### 各要素は ,(カンマ)で区切る

In [3]:
[1,2,3] #一次元配列は列ベクトルであることに注意

3-element Array{Int64,1}:
 1
 2
 3

#### typeを指定する場合は [] の前に行う

In [5]:
Float64[4,5,6]

3-element Array{Float64,1}:
 4.0
 5.0
 6.0

### 二次元配列

In [6]:
[1 2; 3 4] #各要素は空白で区切る

2×2 Array{Int64,2}:
 1  2
 3  4

In [7]:
[1 2  # 2; としても良い
 3 4] # 改行で区切ることもできる(こちらの方が視覚的にわかりやすい)

2×2 Array{Int64,2}:
 1  2
 3  4

In [8]:
[1,2;3,4] # ,(カンマ)は使えないので注意

LoadError: syntax: unexpected semicolon in array expression around In[8]:1

In [10]:
[1;2;3] # 一次元配列と同じ

3-element Array{Int64,1}:
 1
 2
 3

#### Juliaは列優先(column-major order)かつインデックスが1から始める

In [11]:
A = [1 2 3;
       4 5 6;
       7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [13]:
A[1,1] # A[行番号,列番号]

1

In [14]:
A[2,1]

4

### 配列の初期化

In [20]:
#値が初期化されていない配列
Array{Float32}(undef, 3, 4) #Typeの指定が必要

3×4 Array{Float32,2}:
 3.1112f-30   1.0f-45      7.69174f-32  1.0f-45
 1.0f-45      7.69208f-32  1.0f-45      7.67253f-32
 4.53027f-28  1.0f-45      7.67264f-32  1.0f-45

In [21]:
#0で初期化
zeros(Float32,2,3) # Type, 行数, 列数

2×3 Array{Float32,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [22]:
#1で初期化
ones(Float32, 3, 3)

3×3 Array{Float32,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [23]:
#一様分布で初期化
rand(Float32, 3, 3)

3×3 Array{Float32,2}:
 0.629136  0.615609  0.870086
 0.379275  0.01432   0.561568
 0.535654  0.727677  0.241182

In [24]:
#正規分布で初期化
randn(Float32, 3, 3)

3×3 Array{Float32,2}:
 -0.845399   0.759784  2.17317
  0.420293  -0.507191  0.75317
  0.303301  -0.103872  0.631922

In [28]:
#値をxで初期化
fill(10, 3, 3)  #fill(x, 行数, 列数)

3×3 Array{Int64,2}:
 10  10  10
 10  10  10
 10  10  10

In [31]:
#配列Aを値xで初期化
A = zeros(3,3) # まず配列Aを0で初期化

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [33]:
fill!(A,5) # 配列Aを5で初期化

3×3 Array{Float64,2}:
 5.0  5.0  5.0
 5.0  5.0  5.0
 5.0  5.0  5.0

In [41]:
#　配列のサイズを変更
A = [1 2 3 4;
       5 6 7 8;
       9 10 11 12] # (3x4)の配列を作る

3×4 Array{Int64,2}:
 1   2   3   4
 5   6   7   8
 9  10  11  12

In [45]:
reshape(A,4,3) # 配列Aのサイズを(3×4)→(4x3)に変更
# juliaは列優先で配列の順序が変更されていることに注意する。

4×3 Array{Int64,2}:
 1   6  11
 5  10   4
 9   3   8
 2   7  12

#### 配列のcopyとdeepcopy

In [86]:
#配列をcopyする
A = randn(3,3) # Aを正規分布で初期化。randnはTypeを指定しなければ、Float64となる

3×3 Array{Float64,2}:
 -1.58971  0.253964  2.1153
  1.07849  0.115481  0.835929
  1.0754   1.57353   0.639892

In [87]:
 B = A # 配列AをBにcopyする
# ただし、これはただの参照渡しであることに注意

3×3 Array{Float64,2}:
 -1.58971  0.253964  2.1153
  1.07849  0.115481  0.835929
  1.0754   1.57353   0.639892

In [88]:
# 配列Aを確認する
A 

3×3 Array{Float64,2}:
 -1.58971  0.253964  2.1153
  1.07849  0.115481  0.835929
  1.0754   1.57353   0.639892

In [90]:
B[1,1] = 1 # 配列Bの(1,1)成分を1に置き換え

1

In [91]:
# 配列Bを確認する
B 

3×3 Array{Float64,2}:
 1.0      0.253964  2.1153
 1.07849  0.115481  0.835929
 1.0754   1.57353   0.639892

In [92]:
# もう一度配列Aを確認する
A

3×3 Array{Float64,2}:
 1.0      0.253964  2.1153
 1.07849  0.115481  0.835929
 1.0754   1.57353   0.639892

In [ ]:
# B=Aという書き方は参照渡し(リンクを共有していると考えれば良い)ので、
# Bを書き換えるとAまで変わってしまう
# 上記を防ぐためにはcopyを使う

In [93]:
# copy関数
A = randn(3,3) # Aを正規分布で初期化。randnはTypeを指定しなければ、Float64となる

3×3 Array{Float64,2}:
  0.168153   0.697475   0.169452
 -1.03956    0.606535  -0.575409
 -1.95166   -0.429657  -0.369074

In [94]:
B = copy(A)  # 配列AをBにcopyする

3×3 Array{Float64,2}:
  0.168153   0.697475   0.169452
 -1.03956    0.606535  -0.575409
 -1.95166   -0.429657  -0.369074

In [95]:
B[1,1] = 10 # 配列Bの(1,1)成分を10に書き換える

10

In [96]:
# 配列Bを確認する
B

3×3 Array{Float64,2}:
 10.0       0.697475   0.169452
 -1.03956   0.606535  -0.575409
 -1.95166  -0.429657  -0.369074

In [97]:
# 配列Aをもう一度確認する
A # 最初の宣言時と変わっていないことを確認する

3×3 Array{Float64,2}:
  0.168153   0.697475   0.169452
 -1.03956    0.606535  -0.575409
 -1.95166   -0.429657  -0.369074

In [71]:
# 再帰的にコピーしたい場合はdeepcopyを使う
A = [1,2,3] # 配列を要素とした配列を宣言する

3-element Array{Int64,1}:
 1
 2
 3

In [115]:
# ただし、copyでは要素の参照先まではcopyできない
hoge = [1] # 1行1列の配列hogeの宣言

1-element Array{Int64,1}:
 1

In [116]:
A = [hoge, hoge, hoge]

3-element Array{Array{Int64,1},1}:
 [1]
 [1]
 [1]

In [110]:
B = copy(A)

3-element Array{Array{Int64,1},1}:
 [1]
 [1]
 [1]

In [111]:
B[1][1] = 2

2

In [ ]:
hoge

In [112]:
B

3-element Array{Array{Int64,1},1}:
 [2]
 [2]
 [2]

In [113]:
A # copyでは要素の参照先まではcopyできないので、Bを上書きするとAも変わってしまう

3-element Array{Array{Int64,1},1}:
 [2]
 [2]
 [2]

In [117]:
hoge = [3]

1-element Array{Int64,1}:
 3

In [118]:
# 要素の参照先も含めてcopyする場合はdeepcopyを使う
A = [hoge, hoge, hoge]

3-element Array{Array{Int64,1},1}:
 [3]
 [3]
 [3]

In [119]:
B = deepcopy(A)

3-element Array{Array{Int64,1},1}:
 [3]
 [3]
 [3]

In [120]:
B[1][1] = 0

0

In [121]:
B

3-element Array{Array{Int64,1},1}:
 [0]
 [0]
 [0]

In [123]:
A # Aが変わらないことを確認する

3-element Array{Array{Int64,1},1}:
 [3]
 [3]
 [3]

### 配列の演算

#### 配列同士の基本的な四則演算
(配列同士のサイズを揃える)

In [126]:
A = ones(Float32, 3,3) # 1で初期化

3×3 Array{Float32,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [132]:
B = fill(2.0,3,3) # 2で初期化

3×3 Array{Float64,2}:
 2.0  2.0  2.0
 2.0  2.0  2.0
 2.0  2.0  2.0

In [133]:
A + B # AとBの加算

3×3 Array{Float64,2}:
 3.0  3.0  3.0
 3.0  3.0  3.0
 3.0  3.0  3.0

In [134]:
A - B # AとBの減算

3×3 Array{Float64,2}:
 -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0

In [135]:
A * B # AとBの行列の乗算

3×3 Array{Float64,2}:
 6.0  6.0  6.0
 6.0  6.0  6.0
 6.0  6.0  6.0

In [139]:
# スカラーと行列の乗算
c = 10 
c*A

3×3 Array{Float32,2}:
 10.0  10.0  10.0
 10.0  10.0  10.0
 10.0  10.0  10.0

#### 配列の要素同士の演算
配列同士のサイズが異なっている場合でも計算できる(例外あり)

In [142]:
A = ones(Float32,3,3) # 1で初期化

3×3 Array{Float32,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [144]:
B = fill(2,3) # 値が2で初期化された3次元ベクトル

3-element Array{Int64,1}:
 2
 2
 2

In [145]:
# サイズが異なっているので計算できないことを確認する
A + B

LoadError: DimensionMismatch("dimensions must match: a has dims (Base.OneTo(3), Base.OneTo(3)), must have singleton at dim 2")

In [146]:
# サイズが異なっている配列同士の計算にはドット演算子を用いる
A .+ B # Bのサイズは(3x1)だがAに合わせて自動的に(3x3)に拡張される

3×3 Array{Float32,2}:
 3.0  3.0  3.0
 3.0  3.0  3.0
 3.0  3.0  3.0

In [147]:
A .-B

3×3 Array{Float32,2}:
 -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0

In [149]:
# スカラーと配列の演算にもドット演算子が使える
c= 10
 A .+ c

3×3 Array{Float32,2}:
 11.0  11.0  11.0
 11.0  11.0  11.0
 11.0  11.0  11.0

In [150]:
A ./ c

3×3 Array{Float32,2}:
 0.1  0.1  0.1
 0.1  0.1  0.1
 0.1  0.1  0.1

In [151]:
# AとBのサイズが同じ場合、通常の演算とドット演算の結果は一致する
A = ones(Float32,3,3)

3×3 Array{Float32,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [153]:
B = fill(2.0,3,3)

3×3 Array{Float64,2}:
 2.0  2.0  2.0
 2.0  2.0  2.0
 2.0  2.0  2.0

In [154]:
A + B 

3×3 Array{Float64,2}:
 3.0  3.0  3.0
 3.0  3.0  3.0
 3.0  3.0  3.0

In [155]:
A .+ B

3×3 Array{Float64,2}:
 3.0  3.0  3.0
 3.0  3.0  3.0
 3.0  3.0  3.0

### 配列を扱う際に便利な関数

In [161]:
# map関数
A = rand(3,3) # A を一様分布で初期化

3×3 Array{Float64,2}:
 0.278984    0.117572   0.750886
 0.735692    0.0395898  0.581662
 0.00303359  0.850062   0.15775

In [162]:
# 配列Aの全ての要素を10倍する
map(x -> x*10, A) # map(関数, 配列)

3×3 Array{Float64,2}:
 2.78984    1.17572   7.50886
 7.35692    0.395898  5.81662
 0.0303359  8.50062   1.5775

In [170]:
# 配列の末尾に要素を追加する
A = Vector(1:5) # 1~5までの連番で初期化する

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [171]:
push!(A,0) # 配列Aの末尾に0を追加する

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 0

In [172]:
# 末尾の要素の削除にはpop!を使う
pop!(A)

0

In [173]:
A

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [175]:
# 全ての要素の積
reduce(*,A) 

120

In [177]:
# 全ての要素の和
reduce(+,A) 

15

In [178]:
# 全ての要素から奇数のみを取り出す
A = Vector(1:10) # 1~10までの連番で初期化

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [179]:
filter(isodd,A) # filter((評価式), 配列)
# isoddをisevenにすれば偶数を取り出す

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

In [181]:
# 配列の形状や要素を取得する
A = [1,2,3,4,5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [182]:
size(A) # 配列の形状を取得

(5,)

In [183]:
length(A) # 配列の要素数を取得

5

In [189]:
# 行列の場合
A = randn(Float64,3,4)

3×4 Array{Float64,2}:
  0.89175    0.188688  -2.07831   2.57117
  1.05346   -0.301755  -0.556042  1.64002
 -0.242667   0.64704   -0.306413  0.0497813

In [186]:
size(A)

(3, 4)

In [188]:
length(A)

12

In [191]:
# 配列の要素をsortする
A = Vector(5:-1:1) # 初めの要素:step数:最後の要素

5-element Array{Int64,1}:
 5
 4
 3
 2
 1

In [192]:
# 降順→昇順にsortする
sort(A)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [193]:
# 昇順→降順にsortする
sort(A,rev=true)

5-element Array{Int64,1}:
 5
 4
 3
 2
 1