# 科学計算

### 配列操作2

In [1]:
a = Vector(1:3)

3-element Array{Int64,1}:
 1
 2
 3

In [2]:
b = Vector(4:6)

3-element Array{Int64,1}:
 4
 5
 6

In [3]:
[a b]

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

In [4]:
A = [1 2 3; 4 5 6; 7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [5]:
A[1]

1

In [6]:
A[9]

9

In [7]:
A[1,1]

1

In [8]:
A[2, 3]

6

In [9]:
A = Vector(1:9)

9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [10]:
A[begin]

1

In [11]:
A[end]

9

In [12]:
A[begin:end]

9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [13]:
a = Vector(1:9)

9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [14]:
a[2] = 0

0

In [15]:
a

9-element Array{Int64,1}:
 1
 0
 3
 4
 5
 6
 7
 8
 9

In [16]:
a + 1

LoadError: MethodError: no method matching +(::Array{Int64,1}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  +(!Matched::BigInt, ::Union{Int16, Int32, Int64, Int8}) at gmp.jl:530
  +(!Matched::Base.CoreLogging.LogLevel, ::Integer) at logging.jl:116
  ...

In [17]:
a .+ 1

9-element Array{Int64,1}:
  2
  1
  4
  5
  6
  7
  8
  9
 10

In [18]:
a[a .> 4] .= 0

5-element view(::Array{Int64,1}, [5, 6, 7, 8, 9]) with eltype Int64:
 0
 0
 0
 0
 0

In [19]:
a

9-element Array{Int64,1}:
 1
 0
 3
 4
 0
 0
 0
 0
 0

In [20]:
A = reshape(1:9, 3, 3)

3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [21]:
A[5]

5

In [22]:
A[2,3]

8

In [23]:
A[3,3] = 0

LoadError: indexed assignment fails for a reshaped range; consider calling collect

In [24]:
collect(A) #array

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [25]:
B = reshape(1:9, 3, 3)

3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [26]:
Array(A)

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [27]:
A = Array(reshape(1:9,3,3))

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [28]:
#サブ配列

In [29]:
A = rand(3,3)

3×3 Array{Float64,2}:
 0.537637  0.126684  0.203339
 0.072664  0.529189  0.807755
 0.29234   0.36047   0.195772

In [31]:
view(A,:,1)

3-element view(::Array{Float64,2}, :, 1) with eltype Float64:
 0.5376367920004517
 0.07266397240384248
 0.2923400080379348

In [32]:
A = collect(reshape(1:9,3,3))

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [33]:
view(A,:,1)

3-element view(::Array{Int64,2}, :, 1) with eltype Int64:
 1
 2
 3

# ベクトル・行列計算

In [34]:
a = Vector(1:3)

3-element Array{Int64,1}:
 1
 2
 3

In [35]:
b = Vector(4:6)

3-element Array{Int64,1}:
 4
 5
 6

In [36]:
a * b

LoadError: MethodError: no method matching *(::Array{Int64,1}, ::Array{Int64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  *(!Matched::LinearAlgebra.Adjoint{var"#s826",var"#s8261"} where var"#s8261"<:(AbstractArray{T,1} where T) where var"#s826"<:Number, ::AbstractArray{var"#s825",1} where var"#s825"<:Number) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/adjtrans.jl:283
  *(!Matched::LinearAlgebra.Transpose{T,var"#s826"} where var"#s826"<:(AbstractArray{T,1} where T), ::AbstractArray{T,1}) where T<:Real at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/adjtrans.jl:284
  ...

In [37]:
a .* b

3-element Array{Int64,1}:
  4
 10
 18

In [38]:
#内積
using LinearAlgebra

In [39]:
a ⋅ b #\cdot → tabキー

32

In [40]:
dot(a, b)

32

In [41]:
transpose(a) * b

32

In [42]:
a * transpose(b)

3×3 Array{Int64,2}:
  4   5   6
  8  10  12
 12  15  18

In [43]:
# 行列

In [44]:
using LinearAlgebra

In [45]:
Matrix(1.0I, 3,3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [46]:
Array(1I,3,3)



3×3 Array{Int64,2}:
 1  0  0
 0  1  0
 0  0  1

In [47]:
A = Matrix(1.0I, 3,3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [48]:
v = Vector(1:3)

3-element Array{Int64,1}:
 1
 2
 3

In [49]:
A = Array(reshape(1:9,3,3))

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [50]:
c = 2

2

In [51]:
#スカラー倍
A .* c

3×3 Array{Int64,2}:
 2   8  14
 4  10  16
 6  12  18

In [52]:
#行列とベクトルの積
A * v

3-element Array{Int64,1}:
 30
 36
 42

In [53]:
v * A

LoadError: DimensionMismatch("matrix A has dimensions (3,1), matrix B has dimensions (3,3)")

In [54]:
transpose(v) * A

1×3 Transpose{Int64,Array{Int64,1}}:
 14  32  50

In [55]:
B = fill(2,3,3)

3×3 Array{Int64,2}:
 2  2  2
 2  2  2
 2  2  2

In [56]:
A * B

3×3 Array{Int64,2}:
 24  24  24
 30  30  30
 36  36  36

In [57]:
transpose(A)

3×3 Transpose{Int64,Array{Int64,2}}:
 1  2  3
 4  5  6
 7  8  9

In [58]:
A'

3×3 Adjoint{Int64,Array{Int64,2}}:
 1  2  3
 4  5  6
 7  8  9

In [59]:
tr(A)

15

In [60]:
det(A)

0.0

In [61]:
A = [1 2 3; 4 1 6; 7 8 1]

3×3 Array{Int64,2}:
 1  2  3
 4  1  6
 7  8  1

In [62]:
tr(A)

3

In [63]:
det(A)

104.0

In [64]:
inv(A)

3×3 Array{Float64,2}:
 -0.451923   0.211538    0.0865385
  0.365385  -0.192308    0.0576923
  0.240385   0.0576923  -0.0673077

In [66]:
A * inv(A)

3×3 Array{Float64,2}:
  1.0           0.0          -2.77556e-17
 -2.22045e-16   1.0           0.0
  3.88578e-16  -1.38778e-17   1.0

In [68]:
#連立一次方程式Ax＝b

In [69]:
using LinearAlgebra
A = [1 2 3; 4 1 6; 7 8 1]

3×3 Array{Int64,2}:
 1  2  3
 4  1  6
 7  8  1

In [70]:
b = Vector(3:5)

3-element Array{Int64,1}:
 3
 4
 5

In [71]:
inv(A) * b

3-element Array{Float64,1}:
 -0.07692307692307704
  0.6153846153846154
  0.6153846153846154

In [72]:
x = A \ b

3-element Array{Float64,1}:
 -0.07692307692307677
  0.6153846153846153
  0.6153846153846154

### 科学計算いろいろ

In [73]:
#定数

In [74]:
pi

π = 3.1415926535897...

In [76]:
π #\pi → tabキー

π = 3.1415926535897...

In [77]:
#自然対数

In [80]:
ℯ #\euler → tabキー

ℯ = 2.7182818284590...

In [81]:
euler

LoadError: UndefVarError: euler not defined

In [83]:
#平方根
sqrt(2)

1.4142135623730951

In [84]:
#三乗根
cbrt(8)

2.0

In [85]:
#複素数
z = 1 + 2im

1 + 2im

In [86]:
z = complex(1,3)

1 + 3im

In [87]:
real(z)

1

In [88]:
imag(z)

3

In [89]:
conj(z)

1 - 3im

In [90]:
abs(z)

3.1622776601683795

In [91]:
a = -3

-3

In [92]:
abs(a)

3

In [93]:
sign(a)

-1

In [94]:
b = 2
sign(b)

1

In [96]:
c = 0
sign(c) # -1, 0, 1のいずれかが返る

0

In [97]:
#三角関数、指数関数、対数関数

In [98]:
sin(π / 2)

1.0

In [101]:
x = [pi/2, pi, 3/2*pi]
sin.(x)

3-element Array{Float64,1}:
  1.0
  1.2246467991473532e-16
 -1.0

In [102]:
log(2)

0.6931471805599453

In [103]:
log10(1000)

3.0

In [104]:
x = 5
x ^ 3

125

In [106]:
# exp(imθ) = cosθ + im*sinθ
exp(im * π)

-1.0 + 1.2246467991473532e-16im