In [1]:
[1]

1-element Array{Int64,1}:
 1

In [2]:
[1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [3]:
Float64[4,5,6]

3-element Array{Float64,1}:
 4.0
 5.0
 6.0

In [4]:
[1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [5]:
[1 2
    3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [6]:
[1,2 ; 3,4]

LoadError: syntax: unexpected semicolon in array expression around In[6]:1

In [7]:
A = [1 2 3;
    4 5 6;
    7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [8]:
A[1,1]

1

In [9]:
A[2,1]

4

# 初期化

In [11]:
Array{Float32}(undef, 3, 4)

3×4 Array{Float32,2}:
 2.78276f-32  1.0f-45      2.78279f-32    1.0f-45
 1.0f-45      2.78279f-32  1.0f-45      NaN
 2.78277f-32  1.0f-45      2.11498f-32  NaN

In [12]:
zeros(Float32, 2, 3)

2×3 Array{Float32,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [13]:
ones(Float32, 2, 3)

2×3 Array{Float32,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [14]:
randn(Float32, 3, 3)

3×3 Array{Float32,2}:
  0.594939  -0.261027  0.446642
 -1.01523   -0.770617  0.484022
 -2.66952   -1.321     0.529359

In [15]:
fill(100, 3 , 3)

3×3 Array{Int64,2}:
 100  100  100
 100  100  100
 100  100  100

In [16]:
A = [1 2 3 4;
    5 6 7 8;
    9 10 11 12]

3×4 Array{Int64,2}:
 1   2   3   4
 5   6   7   8
 9  10  11  12

In [18]:
#4×3に変える reshape
reshape(A, 4, 3)

4×3 Array{Int64,2}:
 1   6  11
 5  10   4
 9   3   8
 2   7  12

# copyとdeepcopy

In [29]:
A = randn(3,3)

3×3 Array{Float64,2}:
 -1.05795    1.04108   0.717226
 -0.748728   2.03245  -0.916731
  1.90113   -1.64489   0.178625

In [30]:
B = A

3×3 Array{Float64,2}:
 -1.05795    1.04108   0.717226
 -0.748728   2.03245  -0.916731
  1.90113   -1.64489   0.178625

In [31]:
A

3×3 Array{Float64,2}:
 -1.05795    1.04108   0.717226
 -0.748728   2.03245  -0.916731
  1.90113   -1.64489   0.178625

In [32]:
B[1,1] = 1

1

In [33]:
B

3×3 Array{Float64,2}:
  1.0        1.04108   0.717226
 -0.748728   2.03245  -0.916731
  1.90113   -1.64489   0.178625

In [34]:
A

3×3 Array{Float64,2}:
  1.0        1.04108   0.717226
 -0.748728   2.03245  -0.916731
  1.90113   -1.64489   0.178625

In [35]:
A = randn(3,3)

3×3 Array{Float64,2}:
 -2.19157    0.899628   0.576466
  0.810568   1.4432    -0.21364
 -1.01816   -2.21805   -0.884652

In [36]:
B = copy(A)

3×3 Array{Float64,2}:
 -2.19157    0.899628   0.576466
  0.810568   1.4432    -0.21364
 -1.01816   -2.21805   -0.884652

In [37]:
B[1,1] = 10

10

In [38]:
B

3×3 Array{Float64,2}:
 10.0        0.899628   0.576466
  0.810568   1.4432    -0.21364
 -1.01816   -2.21805   -0.884652

In [39]:
A

3×3 Array{Float64,2}:
 -2.19157    0.899628   0.576466
  0.810568   1.4432    -0.21364
 -1.01816   -2.21805   -0.884652

In [40]:
A = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [41]:
hoge = [1]

1-element Array{Int64,1}:
 1

In [42]:
A = [hoge,hoge,hoge]

3-element Array{Array{Int64,1},1}:
 [1]
 [1]
 [1]

In [43]:
B = copy(A)

3-element Array{Array{Int64,1},1}:
 [1]
 [1]
 [1]

In [45]:
B[1][1]=2

2

In [46]:
hoge

1-element Array{Int64,1}:
 2

In [47]:
B

3-element Array{Array{Int64,1},1}:
 [2]
 [2]
 [2]

In [48]:
A

3-element Array{Array{Int64,1},1}:
 [2]
 [2]
 [2]

In [49]:
hoge =[3]

1-element Array{Int64,1}:
 3

In [50]:
A = [hoge,hoge,hoge]

3-element Array{Array{Int64,1},1}:
 [3]
 [3]
 [3]

In [51]:
B = deepcopy(A)

3-element Array{Array{Int64,1},1}:
 [3]
 [3]
 [3]

In [52]:
B[1][1] =0

0

In [53]:
B

3-element Array{Array{Int64,1},1}:
 [0]
 [0]
 [0]

In [54]:
A

3-element Array{Array{Int64,1},1}:
 [3]
 [3]
 [3]

# 配列演算

In [56]:
A = ones(Float32,3,3)

3×3 Array{Float32,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [57]:
B = fill(2.0,3,3)

3×3 Array{Float64,2}:
 2.0  2.0  2.0
 2.0  2.0  2.0
 2.0  2.0  2.0

In [58]:
A + B

3×3 Array{Float64,2}:
 3.0  3.0  3.0
 3.0  3.0  3.0
 3.0  3.0  3.0

In [59]:
A - B

3×3 Array{Float64,2}:
 -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0

In [60]:
A * B #行列

3×3 Array{Float64,2}:
 6.0  6.0  6.0
 6.0  6.0  6.0
 6.0  6.0  6.0

In [61]:
A

3×3 Array{Float32,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [62]:
B

3×3 Array{Float64,2}:
 2.0  2.0  2.0
 2.0  2.0  2.0
 2.0  2.0  2.0

In [63]:
c = 10
c * A

3×3 Array{Float32,2}:
 10.0  10.0  10.0
 10.0  10.0  10.0
 10.0  10.0  10.0

In [64]:
A = ones(Float32,3,3)

3×3 Array{Float32,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [65]:
B = fill(2,3)

3-element Array{Int64,1}:
 2
 2
 2

In [66]:
A + B

LoadError: DimensionMismatch("dimensions must match: a has dims (Base.OneTo(3), Base.OneTo(3)), must have singleton at dim 2")

In [67]:
A .+ B

3×3 Array{Float32,2}:
 3.0  3.0  3.0
 3.0  3.0  3.0
 3.0  3.0  3.0

In [68]:
A .- B

3×3 Array{Float32,2}:
 -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0

In [69]:
c = 10
A .+ c

3×3 Array{Float32,2}:
 11.0  11.0  11.0
 11.0  11.0  11.0
 11.0  11.0  11.0

In [70]:
A ./ c

3×3 Array{Float32,2}:
 0.1  0.1  0.1
 0.1  0.1  0.1
 0.1  0.1  0.1

# 配列を扱うときに便利な関数

In [71]:
A = rand(3,3)

3×3 Array{Float64,2}:
 0.979466  0.58975   0.973404
 0.404465  0.12148   0.8143
 0.368733  0.699634  0.262681

In [72]:
map(x -> x*10, A)

3×3 Array{Float64,2}:
 9.79466  5.8975   9.73404
 4.04465  1.2148   8.143
 3.68733  6.99634  2.62681

In [73]:
A = Vector(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [74]:
push!(A, 0)

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 0

In [75]:
pop!(A)

0

In [76]:
A

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [77]:
reduce(*,A)

120

In [78]:
reduce(+,A)

15

In [79]:
A = Vector(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [80]:
filter(isodd, A)

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

In [81]:
filter(iseven, A)

5-element Array{Int64,1}:
  2
  4
  6
  8
 10

In [82]:
size(A)

(10,)

In [83]:
length(A)

10

In [84]:
#sort
A = Vector(5:-1:1)

5-element Array{Int64,1}:
 5
 4
 3
 2
 1

In [85]:
sort(A)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [86]:
sort(A, rev=true)

5-element Array{Int64,1}:
 5
 4
 3
 2
 1